version: '3'

services:
  PG:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kira
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: code-acl

volumes:
  pg-data:
